version: '2'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      JDBC_DATABASE_URL: jdbc:postgresql://db:5432/postgres
      JDBC_DATABASE_USERNAME: postgres
      JDBC_DATABASE_PASSWORD: postgres
    depends_on:
      - db
    volumes:
      - ./webapp/spring:/opt/webapp
    networks:
      - eist
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./webapp/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - eist

networks:
  eist:
    driver: "bridge"